name: Build and Publish Filter List

on:
    push:
        paths:
            - .github/**
            - scripts/**
            - theme/**
    pull_request:
        paths:
            - .github/**
            - scripts/**
            - theme/**

jobs:
    build_and_publish:
        name: Setup Linux environment
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x

            - name: Install repository dependencies
              run: npm ci

            - name: Build filter list
              run: npm run build-filter-list

            - name: Build filter list personal
              run: npm run build-filter-list-personal

            - name: Publish filter list
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: dist
                  FOLDER: "dist"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
